[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shell_operator"
version = "0.0.5"
authors = [
        { name = "Eugene Shevchenko", email = "evgeny.shevchenko@flant.com" },
]
description = "Python library for Shell Operator"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/flant/py-shell-operator"
"Bug Tracker" = "https://github.com/flant/py-shell-operator/issues"
